FROM golang:1.16

RUN apk update && apk add curl git

RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.21.1/bin/linux/amd64/kubectl
RUN chmod u+x kubectl && mv kubectl /bin/kubectl

WORKDIR /tmp/app

ADD . /tmp/app/

RUN go build -o main .

CMD ["/tmp/app/main"]

EXPOSE 8080