apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ktest
commonLabels:
  env: prod
  group: k8s-api-client
resources:
  - namespace.yaml
  - ../../base
patchesStrategicMerge:
- patches/resource-limits.yaml
- patches/add-labels.yaml