apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-api-client
spec:
  template:
    spec:
      containers:
        - name: k8s-api-client
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "100Mi"
              cpu: "100m"
