apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  namespace: test
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployment-update
  namespace: test
rules:
- apiGroups: [""] 
  resources:
  - pods
  verbs:
  - list
  - watch 
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-update
  namespace: test
subjects:
- kind: ServiceAccount
  name: api
roleRef:
  kind: Role
  name: deployment-update
  apiGroup: ""