name: build
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:

      - name: Set up Go 1.16.3
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.3
        id: go

      - name: Set up path
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        shell: bash

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go mod download
          go mod verify
 
      # - name: Run go lint
      #   run: make lint

      - name: Build
        run: make build


      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     file: ./coverage-all.out
